# Generated by Django 5.1.3 on 2024-11-17 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaveapplication_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['status'], name='leave_leave_status_bdd8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['user'], name='leave_leave_user_id_e47ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['manager'], name='leave_leave_manager_6bd031_idx'),
        ),
    ]
