# Generated by Django 5.1.3 on 2024-11-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveapplication_leave_leave_status_bdd8c8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leaveapplication',
            name='leave_leave_status_bdd8c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaveapplication',
            name='leave_leave_user_id_e47ba0_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaveapplication',
            name='leave_leave_manager_6bd031_idx',
        ),
    ]
