# Generated by Django 5.1.3 on 2024-11-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager')], default=None, max_length=10),
        ),
    ]
